## This file contains two functions: makeCacheMatrix and cacheSolve. 
##  makeCacheMatrix creates a list containing a special matrix that can cache its inverse
##  cacheSolve calculates inverse of the special matrix generated by makeCacheMatrix and return it.
## Importantly, the cacheSolve only calculates the matrix stored in the list generated by makeCacheMatrix.  

## Create a special matrix that can cache its inverse

makeCacheMatrix <- function(x = matrix()) {
    invmat <- matrix()
    set <- function(y=matrix()){
        x <<- y
        invmat <<- matrix()
    }
    get <- function() x
    setinv <- function(solve) invmat <<- solve
    getinv <- function() invmat
    list(set = set, get = get, setinv = setinv, getinv = getinv)
}


## Compute the inverse of the special matrix returned by makeCacheMatrix 
##  1. Calculate if the inverse has not been calculated
##  2. Retrive the inverse if it is already calculated

cacheSolve <- function(x, ...) {
    ## Return a matrix that is the inverse of 'x'
    invmat <- x$getinv()
    if(is.numeric(invmat[1,1])){
        message("getting cached data")
        return(invmat)
    }
    datamat <- x$get()
    invmat <- solve(datamat,...)
    x$setinv(invmat)
    invmat
}
